import { createFileRoute } from "@tanstack/react-router";
import type {} from "@tanstack/react-start";
import { renderSitemap, sitemapResponse, type UrlEntry } from "@/lib/sitemap-xml";

const STATIC_ROUTES: UrlEntry[] = [
  { path: "/", changefreq: "daily", priority: "1.0" },
  { path: "/shop", changefreq: "daily", priority: "0.9" },
  { path: "/collections", changefreq: "weekly", priority: "0.8" },
  { path: "/brands", changefreq: "weekly", priority: "0.7" },
  { path: "/designers", changefreq: "weekly", priority: "0.7" },
  { path: "/limited-finds", changefreq: "daily", priority: "0.8" },
  { path: "/style-quiz", changefreq: "monthly", priority: "0.5" },
  { path: "/swim", changefreq: "weekly", priority: "0.7" },
  { path: "/journal", changefreq: "weekly", priority: "0.6" },
  { path: "/links", changefreq: "monthly", priority: "0.4" },
  { path: "/men", changefreq: "weekly", priority: "0.8" },
  { path: "/women", changefreq: "weekly", priority: "0.8" },
  { path: "/about", changefreq: "monthly", priority: "0.5" },
  { path: "/authentication", changefreq: "monthly", priority: "0.5" },
  { path: "/shipping-returns", changefreq: "monthly", priority: "0.5" },
  { path: "/contact", changefreq: "monthly", priority: "0.5" },
  { path: "/faq", changefreq: "monthly", priority: "0.4" },
  { path: "/privacy", changefreq: "yearly", priority: "0.2" },
  { path: "/terms", changefreq: "yearly", priority: "0.2" },
  { path: "/legal-notice", changefreq: "yearly", priority: "0.2" },
  { path: "/editorial/may-2026", changefreq: "monthly", priority: "0.6" },
  { path: "/editorial/resort-2026", changefreq: "monthly", priority: "0.6" },
  { path: "/editorial/the-new-evening", changefreq: "monthly", priority: "0.6" },
  { path: "/editorial/summer-edit", changefreq: "monthly", priority: "0.6" },
  { path: "/editorial/mens-edit", changefreq: "monthly", priority: "0.6" },
  { path: "/editorial/womens-edit", changefreq: "monthly", priority: "0.6" },
  { path: "/editorial/versace", changefreq: "monthly", priority: "0.6" },
  { path: "/editorial/versace-now", changefreq: "monthly", priority: "0.6" },
  { path: "/editorial/accessories", changefreq: "monthly", priority: "0.6" },
  { path: "/editorial/shoreline-perspective", changefreq: "monthly", priority: "0.6" },
  { path: "/edits/yacht-edit", changefreq: "monthly", priority: "0.6" },
  { path: "/edits/the-prada-effect", changefreq: "monthly", priority: "0.6" },
  { path: "/edits/the-cucinelli-edit", changefreq: "monthly", priority: "0.6" },
  { path: "/edits/the-bag-vault", changefreq: "monthly", priority: "0.6" },
  { path: "/edits/dolce-romana", changefreq: "monthly", priority: "0.6" },
  { path: "/edits/charter-capsule", changefreq: "monthly", priority: "0.6" },
  { path: "/trends/tom-ford-essentials", changefreq: "monthly", priority: "0.6" },
  { path: "/trends/dolce-gabbana-icons", changefreq: "monthly", priority: "0.6" },
  { path: "/trends/pucci-eyewear", changefreq: "monthly", priority: "0.6" },
  { path: "/campaign/mens-swim", changefreq: "weekly", priority: "0.7" },
  { path: "/journal/craftsmanship/spot-real-italian-leather", changefreq: "monthly", priority: "0.7" },
  { path: "/journal/craftsmanship/made-in-italy-vs-designed-in-italy", changefreq: "monthly", priority: "0.7" },
  { path: "/journal/craftsmanship/caring-for-fine-leather", changefreq: "monthly", priority: "0.7" },
  { path: "/journal/style/the-investment-sunglasses-edit", changefreq: "monthly", priority: "0.7" },
  { path: "/journal/style/luxury-sneakers-as-modern-tailoring", changefreq: "monthly", priority: "0.7" },
  { path: "/journal/style/the-cashmere-field-guide", changefreq: "monthly", priority: "0.7" },
  { path: "/collections/italian-leather-wallets", changefreq: "weekly", priority: "0.8" },
  { path: "/collections/italian-leather-loafers", changefreq: "weekly", priority: "0.8" },
  { path: "/collections/designer-mens-shirts", changefreq: "weekly", priority: "0.8" },
  { path: "/collections/italian-leather-handbags", changefreq: "weekly", priority: "0.8" },
  { path: "/collections/designer-sunglasses", changefreq: "weekly", priority: "0.8" },
  { path: "/collections/luxury-sneakers", changefreq: "weekly", priority: "0.8" },
  { path: "/collections/designer-belts", changefreq: "weekly", priority: "0.8" },
  { path: "/collections/cashmere-sweaters", changefreq: "weekly", priority: "0.8" },
  { path: "/collections/silk-scarves", changefreq: "weekly", priority: "0.8" },
  { path: "/collections/designer-crossbody-bags", changefreq: "weekly", priority: "0.8" },
];

export const Route = createFileRoute("/sitemap-static.xml")({
  server: {
    handlers: {
      GET: async () => sitemapResponse(renderSitemap(STATIC_ROUTES)),
    },
  },
});
