/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SwimRouteImport } from './routes/swim'
import { Route as StyleQuizRouteImport } from './routes/style-quiz'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinksRouteImport } from './routes/links'
import { Route as LimitedFindsRouteImport } from './routes/limited-finds'
import { Route as LegalNoticeRouteImport } from './routes/legal-notice'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AuthenticationRouteImport } from './routes/authentication'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as SwimSizeGuideRouteImport } from './routes/swim.size-guide'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as EditorialWomensEditRouteImport } from './routes/editorial.womens-edit'
import { Route as EditorialVersaceNowRouteImport } from './routes/editorial.versace-now'
import { Route as EditorialVersaceRouteImport } from './routes/editorial.versace'
import { Route as EditorialTheNewEveningRouteImport } from './routes/editorial.the-new-evening'
import { Route as EditorialSummerEditRouteImport } from './routes/editorial.summer-edit'
import { Route as EditorialShorelinePerspectiveRouteImport } from './routes/editorial.shoreline-perspective'
import { Route as EditorialResort2026RouteImport } from './routes/editorial.resort-2026'
import { Route as EditorialMensEditRouteImport } from './routes/editorial.mens-edit'
import { Route as EditorialMay2026RouteImport } from './routes/editorial.may-2026'
import { Route as EditorialAccessoriesRouteImport } from './routes/editorial.accessories'
import { Route as CollectionsSilkScarvesRouteImport } from './routes/collections.silk-scarves'
import { Route as CollectionsLuxurySneakersRouteImport } from './routes/collections.luxury-sneakers'
import { Route as CollectionsItalianLeatherWalletsRouteImport } from './routes/collections.italian-leather-wallets'
import { Route as CollectionsItalianLeatherLoafersRouteImport } from './routes/collections.italian-leather-loafers'
import { Route as CollectionsItalianLeatherHandbagsRouteImport } from './routes/collections.italian-leather-handbags'
import { Route as CollectionsDesignerSunglassesRouteImport } from './routes/collections.designer-sunglasses'
import { Route as CollectionsDesignerMensShirtsRouteImport } from './routes/collections.designer-mens-shirts'
import { Route as CollectionsDesignerCrossbodyBagsRouteImport } from './routes/collections.designer-crossbody-bags'
import { Route as CollectionsDesignerBeltsRouteImport } from './routes/collections.designer-belts'
import { Route as CollectionsCashmereSweatersRouteImport } from './routes/collections.cashmere-sweaters'
import { Route as CollectionsHandleRouteImport } from './routes/collections.$handle'
import { Route as CampaignMensSwimRouteImport } from './routes/campaign.mens-swim'
import { Route as BrandVendorRouteImport } from './routes/brand.$vendor'
import { Route as AdminTrendingBrandsRouteImport } from './routes/admin.trending-brands'
import { Route as AdminShopifySyncRouteImport } from './routes/admin.shopify-sync'
import { Route as AdminSeoHealthRouteImport } from './routes/admin.seo-health'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminLandingPagesRouteImport } from './routes/admin.landing-pages'
import { Route as AdminInventorySyncRouteImport } from './routes/admin.inventory-sync'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminHomepageCurationRouteImport } from './routes/admin.homepage-curation'
import { Route as AdminGrowthOsRouteImport } from './routes/admin.growth-os'
import { Route as AdminEmailRecoveryRouteImport } from './routes/admin.email-recovery'
import { Route as AdminCollectionImageQaRouteImport } from './routes/admin.collection-image-qa'
import { Route as AdminCollectionImagePreviewRouteImport } from './routes/admin.collection-image-preview'
import { Route as AdminCollectionHeroRegressionRouteImport } from './routes/admin.collection-hero-regression'
import { Route as AdminCollectionFocalRouteImport } from './routes/admin.collection-focal'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AccountRegisterRouteImport } from './routes/account.register'
import { Route as AccountRecoverRouteImport } from './routes/account.recover'
import { Route as AccountLoginRouteImport } from './routes/account.login'
import { Route as JournalStyleTheInvestmentSunglassesEditRouteImport } from './routes/journal.style.the-investment-sunglasses-edit'
import { Route as JournalStyleLuxurySneakersAsModernTailoringRouteImport } from './routes/journal.style.luxury-sneakers-as-modern-tailoring'
import { Route as JournalCraftsmanshipSpotRealItalianLeatherRouteImport } from './routes/journal.craftsmanship.spot-real-italian-leather'
import { Route as JournalCraftsmanshipMadeInItalyVsDesignedInItalyRouteImport } from './routes/journal.craftsmanship.made-in-italy-vs-designed-in-italy'
import { Route as JournalCraftsmanshipCaringForFineLeatherRouteImport } from './routes/journal.craftsmanship.caring-for-fine-leather'
import { Route as JournalBlogHandleArticleHandleRouteImport } from './routes/journal.$blogHandle.$articleHandle'
import { Route as ApiPublicSeoHealthRouteImport } from './routes/api/public/seo-health'
import { Route as ApiPublicStockAlertsSubscribeRouteImport } from './routes/api/public/stock-alerts/subscribe'
import { Route as ApiPublicHooksSyncCollectionImagesRouteImport } from './routes/api/public/hooks/sync-collection-images'
import { Route as ApiPublicHooksShopifyOrderCreatedRouteImport } from './routes/api/public/hooks/shopify-order-created'
import { Route as ApiPublicHooksExpireShopifyTagsRouteImport } from './routes/api/public/hooks/expire-shopify-tags'
import { Route as ApiPublicHooksDispatchCartRecoveryRouteImport } from './routes/api/public/hooks/dispatch-cart-recovery'
import { Route as ApiPublicCronWinBackEmailsRouteImport } from './routes/api/public/cron/win-back-emails'
import { Route as ApiPublicCronRefreshHomepageLayoutRouteImport } from './routes/api/public/cron/refresh-homepage-layout'
import { Route as ApiPublicCronDrainGrowthJobsRouteImport } from './routes/api/public/cron/drain-growth-jobs'
import { Route as ApiPublicCronBackInStockNotifyRouteImport } from './routes/api/public/cron/back-in-stock-notify'
import { Route as ApiPublicCronAbandonedCartRecoveryRouteImport } from './routes/api/public/cron/abandoned-cart-recovery'
import { Route as ApiPublicAiRecommendationsRouteImport } from './routes/api/public/ai.recommendations'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SwimRoute = SwimRouteImport.update({
  id: '/swim',
  path: '/swim',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleQuizRoute = StyleQuizRouteImport.update({
  id: '/style-quiz',
  path: '/style-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitedFindsRoute = LimitedFindsRouteImport.update({
  id: '/limited-finds',
  path: '/limited-finds',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalNoticeRoute = LegalNoticeRouteImport.update({
  id: '/legal-notice',
  path: '/legal-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationRoute = AuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const SwimSizeGuideRoute = SwimSizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => SwimRoute,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialWomensEditRoute = EditorialWomensEditRouteImport.update({
  id: '/editorial/womens-edit',
  path: '/editorial/womens-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialVersaceNowRoute = EditorialVersaceNowRouteImport.update({
  id: '/editorial/versace-now',
  path: '/editorial/versace-now',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialVersaceRoute = EditorialVersaceRouteImport.update({
  id: '/editorial/versace',
  path: '/editorial/versace',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialTheNewEveningRoute = EditorialTheNewEveningRouteImport.update({
  id: '/editorial/the-new-evening',
  path: '/editorial/the-new-evening',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialSummerEditRoute = EditorialSummerEditRouteImport.update({
  id: '/editorial/summer-edit',
  path: '/editorial/summer-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialShorelinePerspectiveRoute =
  EditorialShorelinePerspectiveRouteImport.update({
    id: '/editorial/shoreline-perspective',
    path: '/editorial/shoreline-perspective',
    getParentRoute: () => rootRouteImport,
  } as any)
const EditorialResort2026Route = EditorialResort2026RouteImport.update({
  id: '/editorial/resort-2026',
  path: '/editorial/resort-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialMensEditRoute = EditorialMensEditRouteImport.update({
  id: '/editorial/mens-edit',
  path: '/editorial/mens-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialMay2026Route = EditorialMay2026RouteImport.update({
  id: '/editorial/may-2026',
  path: '/editorial/may-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialAccessoriesRoute = EditorialAccessoriesRouteImport.update({
  id: '/editorial/accessories',
  path: '/editorial/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSilkScarvesRoute = CollectionsSilkScarvesRouteImport.update({
  id: '/collections/silk-scarves',
  path: '/collections/silk-scarves',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsLuxurySneakersRoute =
  CollectionsLuxurySneakersRouteImport.update({
    id: '/collections/luxury-sneakers',
    path: '/collections/luxury-sneakers',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsItalianLeatherWalletsRoute =
  CollectionsItalianLeatherWalletsRouteImport.update({
    id: '/collections/italian-leather-wallets',
    path: '/collections/italian-leather-wallets',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsItalianLeatherLoafersRoute =
  CollectionsItalianLeatherLoafersRouteImport.update({
    id: '/collections/italian-leather-loafers',
    path: '/collections/italian-leather-loafers',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsItalianLeatherHandbagsRoute =
  CollectionsItalianLeatherHandbagsRouteImport.update({
    id: '/collections/italian-leather-handbags',
    path: '/collections/italian-leather-handbags',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsDesignerSunglassesRoute =
  CollectionsDesignerSunglassesRouteImport.update({
    id: '/collections/designer-sunglasses',
    path: '/collections/designer-sunglasses',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsDesignerMensShirtsRoute =
  CollectionsDesignerMensShirtsRouteImport.update({
    id: '/collections/designer-mens-shirts',
    path: '/collections/designer-mens-shirts',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsDesignerCrossbodyBagsRoute =
  CollectionsDesignerCrossbodyBagsRouteImport.update({
    id: '/collections/designer-crossbody-bags',
    path: '/collections/designer-crossbody-bags',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsDesignerBeltsRoute =
  CollectionsDesignerBeltsRouteImport.update({
    id: '/collections/designer-belts',
    path: '/collections/designer-belts',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsCashmereSweatersRoute =
  CollectionsCashmereSweatersRouteImport.update({
    id: '/collections/cashmere-sweaters',
    path: '/collections/cashmere-sweaters',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignMensSwimRoute = CampaignMensSwimRouteImport.update({
  id: '/campaign/mens-swim',
  path: '/campaign/mens-swim',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandVendorRoute = BrandVendorRouteImport.update({
  id: '/brand/$vendor',
  path: '/brand/$vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrendingBrandsRoute = AdminTrendingBrandsRouteImport.update({
  id: '/admin/trending-brands',
  path: '/admin/trending-brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopifySyncRoute = AdminShopifySyncRouteImport.update({
  id: '/admin/shopify-sync',
  path: '/admin/shopify-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoHealthRoute = AdminSeoHealthRouteImport.update({
  id: '/admin/seo-health',
  path: '/admin/seo-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLandingPagesRoute = AdminLandingPagesRouteImport.update({
  id: '/admin/landing-pages',
  path: '/admin/landing-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventorySyncRoute = AdminInventorySyncRouteImport.update({
  id: '/admin/inventory-sync',
  path: '/admin/inventory-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomepageCurationRoute = AdminHomepageCurationRouteImport.update({
  id: '/admin/homepage-curation',
  path: '/admin/homepage-curation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGrowthOsRoute = AdminGrowthOsRouteImport.update({
  id: '/admin/growth-os',
  path: '/admin/growth-os',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailRecoveryRoute = AdminEmailRecoveryRouteImport.update({
  id: '/admin/email-recovery',
  path: '/admin/email-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionImageQaRoute = AdminCollectionImageQaRouteImport.update({
  id: '/admin/collection-image-qa',
  path: '/admin/collection-image-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionImagePreviewRoute =
  AdminCollectionImagePreviewRouteImport.update({
    id: '/admin/collection-image-preview',
    path: '/admin/collection-image-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCollectionHeroRegressionRoute =
  AdminCollectionHeroRegressionRouteImport.update({
    id: '/admin/collection-hero-regression',
    path: '/admin/collection-hero-regression',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCollectionFocalRoute = AdminCollectionFocalRouteImport.update({
  id: '/admin/collection-focal',
  path: '/admin/collection-focal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRecoverRoute = AccountRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRoute,
} as any)
const JournalStyleTheInvestmentSunglassesEditRoute =
  JournalStyleTheInvestmentSunglassesEditRouteImport.update({
    id: '/style/the-investment-sunglasses-edit',
    path: '/style/the-investment-sunglasses-edit',
    getParentRoute: () => JournalRoute,
  } as any)
const JournalStyleLuxurySneakersAsModernTailoringRoute =
  JournalStyleLuxurySneakersAsModernTailoringRouteImport.update({
    id: '/style/luxury-sneakers-as-modern-tailoring',
    path: '/style/luxury-sneakers-as-modern-tailoring',
    getParentRoute: () => JournalRoute,
  } as any)
const JournalCraftsmanshipSpotRealItalianLeatherRoute =
  JournalCraftsmanshipSpotRealItalianLeatherRouteImport.update({
    id: '/craftsmanship/spot-real-italian-leather',
    path: '/craftsmanship/spot-real-italian-leather',
    getParentRoute: () => JournalRoute,
  } as any)
const JournalCraftsmanshipMadeInItalyVsDesignedInItalyRoute =
  JournalCraftsmanshipMadeInItalyVsDesignedInItalyRouteImport.update({
    id: '/craftsmanship/made-in-italy-vs-designed-in-italy',
    path: '/craftsmanship/made-in-italy-vs-designed-in-italy',
    getParentRoute: () => JournalRoute,
  } as any)
const JournalCraftsmanshipCaringForFineLeatherRoute =
  JournalCraftsmanshipCaringForFineLeatherRouteImport.update({
    id: '/craftsmanship/caring-for-fine-leather',
    path: '/craftsmanship/caring-for-fine-leather',
    getParentRoute: () => JournalRoute,
  } as any)
const JournalBlogHandleArticleHandleRoute =
  JournalBlogHandleArticleHandleRouteImport.update({
    id: '/$blogHandle/$articleHandle',
    path: '/$blogHandle/$articleHandle',
    getParentRoute: () => JournalRoute,
  } as any)
const ApiPublicSeoHealthRoute = ApiPublicSeoHealthRouteImport.update({
  id: '/api/public/seo-health',
  path: '/api/public/seo-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStockAlertsSubscribeRoute =
  ApiPublicStockAlertsSubscribeRouteImport.update({
    id: '/api/public/stock-alerts/subscribe',
    path: '/api/public/stock-alerts/subscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncCollectionImagesRoute =
  ApiPublicHooksSyncCollectionImagesRouteImport.update({
    id: '/api/public/hooks/sync-collection-images',
    path: '/api/public/hooks/sync-collection-images',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksShopifyOrderCreatedRoute =
  ApiPublicHooksShopifyOrderCreatedRouteImport.update({
    id: '/api/public/hooks/shopify-order-created',
    path: '/api/public/hooks/shopify-order-created',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExpireShopifyTagsRoute =
  ApiPublicHooksExpireShopifyTagsRouteImport.update({
    id: '/api/public/hooks/expire-shopify-tags',
    path: '/api/public/hooks/expire-shopify-tags',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchCartRecoveryRoute =
  ApiPublicHooksDispatchCartRecoveryRouteImport.update({
    id: '/api/public/hooks/dispatch-cart-recovery',
    path: '/api/public/hooks/dispatch-cart-recovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronWinBackEmailsRoute =
  ApiPublicCronWinBackEmailsRouteImport.update({
    id: '/api/public/cron/win-back-emails',
    path: '/api/public/cron/win-back-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRefreshHomepageLayoutRoute =
  ApiPublicCronRefreshHomepageLayoutRouteImport.update({
    id: '/api/public/cron/refresh-homepage-layout',
    path: '/api/public/cron/refresh-homepage-layout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDrainGrowthJobsRoute =
  ApiPublicCronDrainGrowthJobsRouteImport.update({
    id: '/api/public/cron/drain-growth-jobs',
    path: '/api/public/cron/drain-growth-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronBackInStockNotifyRoute =
  ApiPublicCronBackInStockNotifyRouteImport.update({
    id: '/api/public/cron/back-in-stock-notify',
    path: '/api/public/cron/back-in-stock-notify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronAbandonedCartRecoveryRoute =
  ApiPublicCronAbandonedCartRecoveryRouteImport.update({
    id: '/api/public/cron/abandoned-cart-recovery',
    path: '/api/public/cron/abandoned-cart-recovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiRecommendationsRoute =
  ApiPublicAiRecommendationsRouteImport.update({
    id: '/api/public/ai/recommendations',
    path: '/api/public/ai/recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/authentication': typeof AuthenticationRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRouteWithChildren
  '/legal-notice': typeof LegalNoticeRoute
  '/limited-finds': typeof LimitedFindsRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/privacy': typeof PrivacyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/style-quiz': typeof StyleQuizRoute
  '/swim': typeof SwimRouteWithChildren
  '/terms': typeof TermsRoute
  '/account/login': typeof AccountLoginRoute
  '/account/recover': typeof AccountRecoverRoute
  '/account/register': typeof AccountRegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/collection-focal': typeof AdminCollectionFocalRoute
  '/admin/collection-hero-regression': typeof AdminCollectionHeroRegressionRoute
  '/admin/collection-image-preview': typeof AdminCollectionImagePreviewRoute
  '/admin/collection-image-qa': typeof AdminCollectionImageQaRoute
  '/admin/email-recovery': typeof AdminEmailRecoveryRoute
  '/admin/growth-os': typeof AdminGrowthOsRoute
  '/admin/homepage-curation': typeof AdminHomepageCurationRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/inventory-sync': typeof AdminInventorySyncRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo-health': typeof AdminSeoHealthRoute
  '/admin/shopify-sync': typeof AdminShopifySyncRoute
  '/admin/trending-brands': typeof AdminTrendingBrandsRoute
  '/brand/$vendor': typeof BrandVendorRoute
  '/campaign/mens-swim': typeof CampaignMensSwimRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/collections/cashmere-sweaters': typeof CollectionsCashmereSweatersRoute
  '/collections/designer-belts': typeof CollectionsDesignerBeltsRoute
  '/collections/designer-crossbody-bags': typeof CollectionsDesignerCrossbodyBagsRoute
  '/collections/designer-mens-shirts': typeof CollectionsDesignerMensShirtsRoute
  '/collections/designer-sunglasses': typeof CollectionsDesignerSunglassesRoute
  '/collections/italian-leather-handbags': typeof CollectionsItalianLeatherHandbagsRoute
  '/collections/italian-leather-loafers': typeof CollectionsItalianLeatherLoafersRoute
  '/collections/italian-leather-wallets': typeof CollectionsItalianLeatherWalletsRoute
  '/collections/luxury-sneakers': typeof CollectionsLuxurySneakersRoute
  '/collections/silk-scarves': typeof CollectionsSilkScarvesRoute
  '/editorial/accessories': typeof EditorialAccessoriesRoute
  '/editorial/may-2026': typeof EditorialMay2026Route
  '/editorial/mens-edit': typeof EditorialMensEditRoute
  '/editorial/resort-2026': typeof EditorialResort2026Route
  '/editorial/shoreline-perspective': typeof EditorialShorelinePerspectiveRoute
  '/editorial/summer-edit': typeof EditorialSummerEditRoute
  '/editorial/the-new-evening': typeof EditorialTheNewEveningRoute
  '/editorial/versace': typeof EditorialVersaceRoute
  '/editorial/versace-now': typeof EditorialVersaceNowRoute
  '/editorial/womens-edit': typeof EditorialWomensEditRoute
  '/product/$handle': typeof ProductHandleRoute
  '/swim/size-guide': typeof SwimSizeGuideRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/api/public/seo-health': typeof ApiPublicSeoHealthRoute
  '/journal/$blogHandle/$articleHandle': typeof JournalBlogHandleArticleHandleRoute
  '/journal/craftsmanship/caring-for-fine-leather': typeof JournalCraftsmanshipCaringForFineLeatherRoute
  '/journal/craftsmanship/made-in-italy-vs-designed-in-italy': typeof JournalCraftsmanshipMadeInItalyVsDesignedInItalyRoute
  '/journal/craftsmanship/spot-real-italian-leather': typeof JournalCraftsmanshipSpotRealItalianLeatherRoute
  '/journal/style/luxury-sneakers-as-modern-tailoring': typeof JournalStyleLuxurySneakersAsModernTailoringRoute
  '/journal/style/the-investment-sunglasses-edit': typeof JournalStyleTheInvestmentSunglassesEditRoute
  '/api/public/ai/recommendations': typeof ApiPublicAiRecommendationsRoute
  '/api/public/cron/abandoned-cart-recovery': typeof ApiPublicCronAbandonedCartRecoveryRoute
  '/api/public/cron/back-in-stock-notify': typeof ApiPublicCronBackInStockNotifyRoute
  '/api/public/cron/drain-growth-jobs': typeof ApiPublicCronDrainGrowthJobsRoute
  '/api/public/cron/refresh-homepage-layout': typeof ApiPublicCronRefreshHomepageLayoutRoute
  '/api/public/cron/win-back-emails': typeof ApiPublicCronWinBackEmailsRoute
  '/api/public/hooks/dispatch-cart-recovery': typeof ApiPublicHooksDispatchCartRecoveryRoute
  '/api/public/hooks/expire-shopify-tags': typeof ApiPublicHooksExpireShopifyTagsRoute
  '/api/public/hooks/shopify-order-created': typeof ApiPublicHooksShopifyOrderCreatedRoute
  '/api/public/hooks/sync-collection-images': typeof ApiPublicHooksSyncCollectionImagesRoute
  '/api/public/stock-alerts/subscribe': typeof ApiPublicStockAlertsSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authentication': typeof AuthenticationRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRouteWithChildren
  '/legal-notice': typeof LegalNoticeRoute
  '/limited-finds': typeof LimitedFindsRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/privacy': typeof PrivacyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/style-quiz': typeof StyleQuizRoute
  '/swim': typeof SwimRouteWithChildren
  '/terms': typeof TermsRoute
  '/account/login': typeof AccountLoginRoute
  '/account/recover': typeof AccountRecoverRoute
  '/account/register': typeof AccountRegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/collection-focal': typeof AdminCollectionFocalRoute
  '/admin/collection-hero-regression': typeof AdminCollectionHeroRegressionRoute
  '/admin/collection-image-preview': typeof AdminCollectionImagePreviewRoute
  '/admin/collection-image-qa': typeof AdminCollectionImageQaRoute
  '/admin/email-recovery': typeof AdminEmailRecoveryRoute
  '/admin/growth-os': typeof AdminGrowthOsRoute
  '/admin/homepage-curation': typeof AdminHomepageCurationRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/inventory-sync': typeof AdminInventorySyncRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo-health': typeof AdminSeoHealthRoute
  '/admin/shopify-sync': typeof AdminShopifySyncRoute
  '/admin/trending-brands': typeof AdminTrendingBrandsRoute
  '/brand/$vendor': typeof BrandVendorRoute
  '/campaign/mens-swim': typeof CampaignMensSwimRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/collections/cashmere-sweaters': typeof CollectionsCashmereSweatersRoute
  '/collections/designer-belts': typeof CollectionsDesignerBeltsRoute
  '/collections/designer-crossbody-bags': typeof CollectionsDesignerCrossbodyBagsRoute
  '/collections/designer-mens-shirts': typeof CollectionsDesignerMensShirtsRoute
  '/collections/designer-sunglasses': typeof CollectionsDesignerSunglassesRoute
  '/collections/italian-leather-handbags': typeof CollectionsItalianLeatherHandbagsRoute
  '/collections/italian-leather-loafers': typeof CollectionsItalianLeatherLoafersRoute
  '/collections/italian-leather-wallets': typeof CollectionsItalianLeatherWalletsRoute
  '/collections/luxury-sneakers': typeof CollectionsLuxurySneakersRoute
  '/collections/silk-scarves': typeof CollectionsSilkScarvesRoute
  '/editorial/accessories': typeof EditorialAccessoriesRoute
  '/editorial/may-2026': typeof EditorialMay2026Route
  '/editorial/mens-edit': typeof EditorialMensEditRoute
  '/editorial/resort-2026': typeof EditorialResort2026Route
  '/editorial/shoreline-perspective': typeof EditorialShorelinePerspectiveRoute
  '/editorial/summer-edit': typeof EditorialSummerEditRoute
  '/editorial/the-new-evening': typeof EditorialTheNewEveningRoute
  '/editorial/versace': typeof EditorialVersaceRoute
  '/editorial/versace-now': typeof EditorialVersaceNowRoute
  '/editorial/womens-edit': typeof EditorialWomensEditRoute
  '/product/$handle': typeof ProductHandleRoute
  '/swim/size-guide': typeof SwimSizeGuideRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/api/public/seo-health': typeof ApiPublicSeoHealthRoute
  '/journal/$blogHandle/$articleHandle': typeof JournalBlogHandleArticleHandleRoute
  '/journal/craftsmanship/caring-for-fine-leather': typeof JournalCraftsmanshipCaringForFineLeatherRoute
  '/journal/craftsmanship/made-in-italy-vs-designed-in-italy': typeof JournalCraftsmanshipMadeInItalyVsDesignedInItalyRoute
  '/journal/craftsmanship/spot-real-italian-leather': typeof JournalCraftsmanshipSpotRealItalianLeatherRoute
  '/journal/style/luxury-sneakers-as-modern-tailoring': typeof JournalStyleLuxurySneakersAsModernTailoringRoute
  '/journal/style/the-investment-sunglasses-edit': typeof JournalStyleTheInvestmentSunglassesEditRoute
  '/api/public/ai/recommendations': typeof ApiPublicAiRecommendationsRoute
  '/api/public/cron/abandoned-cart-recovery': typeof ApiPublicCronAbandonedCartRecoveryRoute
  '/api/public/cron/back-in-stock-notify': typeof ApiPublicCronBackInStockNotifyRoute
  '/api/public/cron/drain-growth-jobs': typeof ApiPublicCronDrainGrowthJobsRoute
  '/api/public/cron/refresh-homepage-layout': typeof ApiPublicCronRefreshHomepageLayoutRoute
  '/api/public/cron/win-back-emails': typeof ApiPublicCronWinBackEmailsRoute
  '/api/public/hooks/dispatch-cart-recovery': typeof ApiPublicHooksDispatchCartRecoveryRoute
  '/api/public/hooks/expire-shopify-tags': typeof ApiPublicHooksExpireShopifyTagsRoute
  '/api/public/hooks/shopify-order-created': typeof ApiPublicHooksShopifyOrderCreatedRoute
  '/api/public/hooks/sync-collection-images': typeof ApiPublicHooksSyncCollectionImagesRoute
  '/api/public/stock-alerts/subscribe': typeof ApiPublicStockAlertsSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/authentication': typeof AuthenticationRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRouteWithChildren
  '/legal-notice': typeof LegalNoticeRoute
  '/limited-finds': typeof LimitedFindsRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/privacy': typeof PrivacyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/style-quiz': typeof StyleQuizRoute
  '/swim': typeof SwimRouteWithChildren
  '/terms': typeof TermsRoute
  '/account/login': typeof AccountLoginRoute
  '/account/recover': typeof AccountRecoverRoute
  '/account/register': typeof AccountRegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/collection-focal': typeof AdminCollectionFocalRoute
  '/admin/collection-hero-regression': typeof AdminCollectionHeroRegressionRoute
  '/admin/collection-image-preview': typeof AdminCollectionImagePreviewRoute
  '/admin/collection-image-qa': typeof AdminCollectionImageQaRoute
  '/admin/email-recovery': typeof AdminEmailRecoveryRoute
  '/admin/growth-os': typeof AdminGrowthOsRoute
  '/admin/homepage-curation': typeof AdminHomepageCurationRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/inventory-sync': typeof AdminInventorySyncRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo-health': typeof AdminSeoHealthRoute
  '/admin/shopify-sync': typeof AdminShopifySyncRoute
  '/admin/trending-brands': typeof AdminTrendingBrandsRoute
  '/brand/$vendor': typeof BrandVendorRoute
  '/campaign/mens-swim': typeof CampaignMensSwimRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/collections/cashmere-sweaters': typeof CollectionsCashmereSweatersRoute
  '/collections/designer-belts': typeof CollectionsDesignerBeltsRoute
  '/collections/designer-crossbody-bags': typeof CollectionsDesignerCrossbodyBagsRoute
  '/collections/designer-mens-shirts': typeof CollectionsDesignerMensShirtsRoute
  '/collections/designer-sunglasses': typeof CollectionsDesignerSunglassesRoute
  '/collections/italian-leather-handbags': typeof CollectionsItalianLeatherHandbagsRoute
  '/collections/italian-leather-loafers': typeof CollectionsItalianLeatherLoafersRoute
  '/collections/italian-leather-wallets': typeof CollectionsItalianLeatherWalletsRoute
  '/collections/luxury-sneakers': typeof CollectionsLuxurySneakersRoute
  '/collections/silk-scarves': typeof CollectionsSilkScarvesRoute
  '/editorial/accessories': typeof EditorialAccessoriesRoute
  '/editorial/may-2026': typeof EditorialMay2026Route
  '/editorial/mens-edit': typeof EditorialMensEditRoute
  '/editorial/resort-2026': typeof EditorialResort2026Route
  '/editorial/shoreline-perspective': typeof EditorialShorelinePerspectiveRoute
  '/editorial/summer-edit': typeof EditorialSummerEditRoute
  '/editorial/the-new-evening': typeof EditorialTheNewEveningRoute
  '/editorial/versace': typeof EditorialVersaceRoute
  '/editorial/versace-now': typeof EditorialVersaceNowRoute
  '/editorial/womens-edit': typeof EditorialWomensEditRoute
  '/product/$handle': typeof ProductHandleRoute
  '/swim/size-guide': typeof SwimSizeGuideRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/api/public/seo-health': typeof ApiPublicSeoHealthRoute
  '/journal/$blogHandle/$articleHandle': typeof JournalBlogHandleArticleHandleRoute
  '/journal/craftsmanship/caring-for-fine-leather': typeof JournalCraftsmanshipCaringForFineLeatherRoute
  '/journal/craftsmanship/made-in-italy-vs-designed-in-italy': typeof JournalCraftsmanshipMadeInItalyVsDesignedInItalyRoute
  '/journal/craftsmanship/spot-real-italian-leather': typeof JournalCraftsmanshipSpotRealItalianLeatherRoute
  '/journal/style/luxury-sneakers-as-modern-tailoring': typeof JournalStyleLuxurySneakersAsModernTailoringRoute
  '/journal/style/the-investment-sunglasses-edit': typeof JournalStyleTheInvestmentSunglassesEditRoute
  '/api/public/ai/recommendations': typeof ApiPublicAiRecommendationsRoute
  '/api/public/cron/abandoned-cart-recovery': typeof ApiPublicCronAbandonedCartRecoveryRoute
  '/api/public/cron/back-in-stock-notify': typeof ApiPublicCronBackInStockNotifyRoute
  '/api/public/cron/drain-growth-jobs': typeof ApiPublicCronDrainGrowthJobsRoute
  '/api/public/cron/refresh-homepage-layout': typeof ApiPublicCronRefreshHomepageLayoutRoute
  '/api/public/cron/win-back-emails': typeof ApiPublicCronWinBackEmailsRoute
  '/api/public/hooks/dispatch-cart-recovery': typeof ApiPublicHooksDispatchCartRecoveryRoute
  '/api/public/hooks/expire-shopify-tags': typeof ApiPublicHooksExpireShopifyTagsRoute
  '/api/public/hooks/shopify-order-created': typeof ApiPublicHooksShopifyOrderCreatedRoute
  '/api/public/hooks/sync-collection-images': typeof ApiPublicHooksSyncCollectionImagesRoute
  '/api/public/stock-alerts/subscribe': typeof ApiPublicStockAlertsSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/authentication'
    | '/brands'
    | '/contact'
    | '/faq'
    | '/journal'
    | '/legal-notice'
    | '/limited-finds'
    | '/links'
    | '/login'
    | '/order-confirmed'
    | '/privacy'
    | '/shipping-returns'
    | '/shop'
    | '/sitemap.xml'
    | '/style-quiz'
    | '/swim'
    | '/terms'
    | '/account/login'
    | '/account/recover'
    | '/account/register'
    | '/admin/analytics'
    | '/admin/collection-focal'
    | '/admin/collection-hero-regression'
    | '/admin/collection-image-preview'
    | '/admin/collection-image-qa'
    | '/admin/email-recovery'
    | '/admin/growth-os'
    | '/admin/homepage-curation'
    | '/admin/inbox'
    | '/admin/inventory-sync'
    | '/admin/landing-pages'
    | '/admin/reviews'
    | '/admin/seo-health'
    | '/admin/shopify-sync'
    | '/admin/trending-brands'
    | '/brand/$vendor'
    | '/campaign/mens-swim'
    | '/collections/$handle'
    | '/collections/cashmere-sweaters'
    | '/collections/designer-belts'
    | '/collections/designer-crossbody-bags'
    | '/collections/designer-mens-shirts'
    | '/collections/designer-sunglasses'
    | '/collections/italian-leather-handbags'
    | '/collections/italian-leather-loafers'
    | '/collections/italian-leather-wallets'
    | '/collections/luxury-sneakers'
    | '/collections/silk-scarves'
    | '/editorial/accessories'
    | '/editorial/may-2026'
    | '/editorial/mens-edit'
    | '/editorial/resort-2026'
    | '/editorial/shoreline-perspective'
    | '/editorial/summer-edit'
    | '/editorial/the-new-evening'
    | '/editorial/versace'
    | '/editorial/versace-now'
    | '/editorial/womens-edit'
    | '/product/$handle'
    | '/swim/size-guide'
    | '/account/'
    | '/admin/'
    | '/collections/'
    | '/api/public/seo-health'
    | '/journal/$blogHandle/$articleHandle'
    | '/journal/craftsmanship/caring-for-fine-leather'
    | '/journal/craftsmanship/made-in-italy-vs-designed-in-italy'
    | '/journal/craftsmanship/spot-real-italian-leather'
    | '/journal/style/luxury-sneakers-as-modern-tailoring'
    | '/journal/style/the-investment-sunglasses-edit'
    | '/api/public/ai/recommendations'
    | '/api/public/cron/abandoned-cart-recovery'
    | '/api/public/cron/back-in-stock-notify'
    | '/api/public/cron/drain-growth-jobs'
    | '/api/public/cron/refresh-homepage-layout'
    | '/api/public/cron/win-back-emails'
    | '/api/public/hooks/dispatch-cart-recovery'
    | '/api/public/hooks/expire-shopify-tags'
    | '/api/public/hooks/shopify-order-created'
    | '/api/public/hooks/sync-collection-images'
    | '/api/public/stock-alerts/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/authentication'
    | '/brands'
    | '/contact'
    | '/faq'
    | '/journal'
    | '/legal-notice'
    | '/limited-finds'
    | '/links'
    | '/login'
    | '/order-confirmed'
    | '/privacy'
    | '/shipping-returns'
    | '/shop'
    | '/sitemap.xml'
    | '/style-quiz'
    | '/swim'
    | '/terms'
    | '/account/login'
    | '/account/recover'
    | '/account/register'
    | '/admin/analytics'
    | '/admin/collection-focal'
    | '/admin/collection-hero-regression'
    | '/admin/collection-image-preview'
    | '/admin/collection-image-qa'
    | '/admin/email-recovery'
    | '/admin/growth-os'
    | '/admin/homepage-curation'
    | '/admin/inbox'
    | '/admin/inventory-sync'
    | '/admin/landing-pages'
    | '/admin/reviews'
    | '/admin/seo-health'
    | '/admin/shopify-sync'
    | '/admin/trending-brands'
    | '/brand/$vendor'
    | '/campaign/mens-swim'
    | '/collections/$handle'
    | '/collections/cashmere-sweaters'
    | '/collections/designer-belts'
    | '/collections/designer-crossbody-bags'
    | '/collections/designer-mens-shirts'
    | '/collections/designer-sunglasses'
    | '/collections/italian-leather-handbags'
    | '/collections/italian-leather-loafers'
    | '/collections/italian-leather-wallets'
    | '/collections/luxury-sneakers'
    | '/collections/silk-scarves'
    | '/editorial/accessories'
    | '/editorial/may-2026'
    | '/editorial/mens-edit'
    | '/editorial/resort-2026'
    | '/editorial/shoreline-perspective'
    | '/editorial/summer-edit'
    | '/editorial/the-new-evening'
    | '/editorial/versace'
    | '/editorial/versace-now'
    | '/editorial/womens-edit'
    | '/product/$handle'
    | '/swim/size-guide'
    | '/account'
    | '/admin'
    | '/collections'
    | '/api/public/seo-health'
    | '/journal/$blogHandle/$articleHandle'
    | '/journal/craftsmanship/caring-for-fine-leather'
    | '/journal/craftsmanship/made-in-italy-vs-designed-in-italy'
    | '/journal/craftsmanship/spot-real-italian-leather'
    | '/journal/style/luxury-sneakers-as-modern-tailoring'
    | '/journal/style/the-investment-sunglasses-edit'
    | '/api/public/ai/recommendations'
    | '/api/public/cron/abandoned-cart-recovery'
    | '/api/public/cron/back-in-stock-notify'
    | '/api/public/cron/drain-growth-jobs'
    | '/api/public/cron/refresh-homepage-layout'
    | '/api/public/cron/win-back-emails'
    | '/api/public/hooks/dispatch-cart-recovery'
    | '/api/public/hooks/expire-shopify-tags'
    | '/api/public/hooks/shopify-order-created'
    | '/api/public/hooks/sync-collection-images'
    | '/api/public/stock-alerts/subscribe'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/authentication'
    | '/brands'
    | '/contact'
    | '/faq'
    | '/journal'
    | '/legal-notice'
    | '/limited-finds'
    | '/links'
    | '/login'
    | '/order-confirmed'
    | '/privacy'
    | '/shipping-returns'
    | '/shop'
    | '/sitemap.xml'
    | '/style-quiz'
    | '/swim'
    | '/terms'
    | '/account/login'
    | '/account/recover'
    | '/account/register'
    | '/admin/analytics'
    | '/admin/collection-focal'
    | '/admin/collection-hero-regression'
    | '/admin/collection-image-preview'
    | '/admin/collection-image-qa'
    | '/admin/email-recovery'
    | '/admin/growth-os'
    | '/admin/homepage-curation'
    | '/admin/inbox'
    | '/admin/inventory-sync'
    | '/admin/landing-pages'
    | '/admin/reviews'
    | '/admin/seo-health'
    | '/admin/shopify-sync'
    | '/admin/trending-brands'
    | '/brand/$vendor'
    | '/campaign/mens-swim'
    | '/collections/$handle'
    | '/collections/cashmere-sweaters'
    | '/collections/designer-belts'
    | '/collections/designer-crossbody-bags'
    | '/collections/designer-mens-shirts'
    | '/collections/designer-sunglasses'
    | '/collections/italian-leather-handbags'
    | '/collections/italian-leather-loafers'
    | '/collections/italian-leather-wallets'
    | '/collections/luxury-sneakers'
    | '/collections/silk-scarves'
    | '/editorial/accessories'
    | '/editorial/may-2026'
    | '/editorial/mens-edit'
    | '/editorial/resort-2026'
    | '/editorial/shoreline-perspective'
    | '/editorial/summer-edit'
    | '/editorial/the-new-evening'
    | '/editorial/versace'
    | '/editorial/versace-now'
    | '/editorial/womens-edit'
    | '/product/$handle'
    | '/swim/size-guide'
    | '/account/'
    | '/admin/'
    | '/collections/'
    | '/api/public/seo-health'
    | '/journal/$blogHandle/$articleHandle'
    | '/journal/craftsmanship/caring-for-fine-leather'
    | '/journal/craftsmanship/made-in-italy-vs-designed-in-italy'
    | '/journal/craftsmanship/spot-real-italian-leather'
    | '/journal/style/luxury-sneakers-as-modern-tailoring'
    | '/journal/style/the-investment-sunglasses-edit'
    | '/api/public/ai/recommendations'
    | '/api/public/cron/abandoned-cart-recovery'
    | '/api/public/cron/back-in-stock-notify'
    | '/api/public/cron/drain-growth-jobs'
    | '/api/public/cron/refresh-homepage-layout'
    | '/api/public/cron/win-back-emails'
    | '/api/public/hooks/dispatch-cart-recovery'
    | '/api/public/hooks/expire-shopify-tags'
    | '/api/public/hooks/shopify-order-created'
    | '/api/public/hooks/sync-collection-images'
    | '/api/public/stock-alerts/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AuthenticationRoute: typeof AuthenticationRoute
  BrandsRoute: typeof BrandsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  JournalRoute: typeof JournalRouteWithChildren
  LegalNoticeRoute: typeof LegalNoticeRoute
  LimitedFindsRoute: typeof LimitedFindsRoute
  LinksRoute: typeof LinksRoute
  LoginRoute: typeof LoginRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  PrivacyRoute: typeof PrivacyRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StyleQuizRoute: typeof StyleQuizRoute
  SwimRoute: typeof SwimRouteWithChildren
  TermsRoute: typeof TermsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCollectionFocalRoute: typeof AdminCollectionFocalRoute
  AdminCollectionHeroRegressionRoute: typeof AdminCollectionHeroRegressionRoute
  AdminCollectionImagePreviewRoute: typeof AdminCollectionImagePreviewRoute
  AdminCollectionImageQaRoute: typeof AdminCollectionImageQaRoute
  AdminEmailRecoveryRoute: typeof AdminEmailRecoveryRoute
  AdminGrowthOsRoute: typeof AdminGrowthOsRoute
  AdminHomepageCurationRoute: typeof AdminHomepageCurationRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminInventorySyncRoute: typeof AdminInventorySyncRoute
  AdminLandingPagesRoute: typeof AdminLandingPagesRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSeoHealthRoute: typeof AdminSeoHealthRoute
  AdminShopifySyncRoute: typeof AdminShopifySyncRoute
  AdminTrendingBrandsRoute: typeof AdminTrendingBrandsRoute
  BrandVendorRoute: typeof BrandVendorRoute
  CampaignMensSwimRoute: typeof CampaignMensSwimRoute
  CollectionsHandleRoute: typeof CollectionsHandleRoute
  CollectionsCashmereSweatersRoute: typeof CollectionsCashmereSweatersRoute
  CollectionsDesignerBeltsRoute: typeof CollectionsDesignerBeltsRoute
  CollectionsDesignerCrossbodyBagsRoute: typeof CollectionsDesignerCrossbodyBagsRoute
  CollectionsDesignerMensShirtsRoute: typeof CollectionsDesignerMensShirtsRoute
  CollectionsDesignerSunglassesRoute: typeof CollectionsDesignerSunglassesRoute
  CollectionsItalianLeatherHandbagsRoute: typeof CollectionsItalianLeatherHandbagsRoute
  CollectionsItalianLeatherLoafersRoute: typeof CollectionsItalianLeatherLoafersRoute
  CollectionsItalianLeatherWalletsRoute: typeof CollectionsItalianLeatherWalletsRoute
  CollectionsLuxurySneakersRoute: typeof CollectionsLuxurySneakersRoute
  CollectionsSilkScarvesRoute: typeof CollectionsSilkScarvesRoute
  EditorialAccessoriesRoute: typeof EditorialAccessoriesRoute
  EditorialMay2026Route: typeof EditorialMay2026Route
  EditorialMensEditRoute: typeof EditorialMensEditRoute
  EditorialResort2026Route: typeof EditorialResort2026Route
  EditorialShorelinePerspectiveRoute: typeof EditorialShorelinePerspectiveRoute
  EditorialSummerEditRoute: typeof EditorialSummerEditRoute
  EditorialTheNewEveningRoute: typeof EditorialTheNewEveningRoute
  EditorialVersaceRoute: typeof EditorialVersaceRoute
  EditorialVersaceNowRoute: typeof EditorialVersaceNowRoute
  EditorialWomensEditRoute: typeof EditorialWomensEditRoute
  ProductHandleRoute: typeof ProductHandleRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ApiPublicSeoHealthRoute: typeof ApiPublicSeoHealthRoute
  ApiPublicAiRecommendationsRoute: typeof ApiPublicAiRecommendationsRoute
  ApiPublicCronAbandonedCartRecoveryRoute: typeof ApiPublicCronAbandonedCartRecoveryRoute
  ApiPublicCronBackInStockNotifyRoute: typeof ApiPublicCronBackInStockNotifyRoute
  ApiPublicCronDrainGrowthJobsRoute: typeof ApiPublicCronDrainGrowthJobsRoute
  ApiPublicCronRefreshHomepageLayoutRoute: typeof ApiPublicCronRefreshHomepageLayoutRoute
  ApiPublicCronWinBackEmailsRoute: typeof ApiPublicCronWinBackEmailsRoute
  ApiPublicHooksDispatchCartRecoveryRoute: typeof ApiPublicHooksDispatchCartRecoveryRoute
  ApiPublicHooksExpireShopifyTagsRoute: typeof ApiPublicHooksExpireShopifyTagsRoute
  ApiPublicHooksShopifyOrderCreatedRoute: typeof ApiPublicHooksShopifyOrderCreatedRoute
  ApiPublicHooksSyncCollectionImagesRoute: typeof ApiPublicHooksSyncCollectionImagesRoute
  ApiPublicStockAlertsSubscribeRoute: typeof ApiPublicStockAlertsSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swim': {
      id: '/swim'
      path: '/swim'
      fullPath: '/swim'
      preLoaderRoute: typeof SwimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-quiz': {
      id: '/style-quiz'
      path: '/style-quiz'
      fullPath: '/style-quiz'
      preLoaderRoute: typeof StyleQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limited-finds': {
      id: '/limited-finds'
      path: '/limited-finds'
      fullPath: '/limited-finds'
      preLoaderRoute: typeof LimitedFindsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-notice': {
      id: '/legal-notice'
      path: '/legal-notice'
      fullPath: '/legal-notice'
      preLoaderRoute: typeof LegalNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication': {
      id: '/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/swim/size-guide': {
      id: '/swim/size-guide'
      path: '/size-guide'
      fullPath: '/swim/size-guide'
      preLoaderRoute: typeof SwimSizeGuideRouteImport
      parentRoute: typeof SwimRoute
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/womens-edit': {
      id: '/editorial/womens-edit'
      path: '/editorial/womens-edit'
      fullPath: '/editorial/womens-edit'
      preLoaderRoute: typeof EditorialWomensEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/versace-now': {
      id: '/editorial/versace-now'
      path: '/editorial/versace-now'
      fullPath: '/editorial/versace-now'
      preLoaderRoute: typeof EditorialVersaceNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/versace': {
      id: '/editorial/versace'
      path: '/editorial/versace'
      fullPath: '/editorial/versace'
      preLoaderRoute: typeof EditorialVersaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/the-new-evening': {
      id: '/editorial/the-new-evening'
      path: '/editorial/the-new-evening'
      fullPath: '/editorial/the-new-evening'
      preLoaderRoute: typeof EditorialTheNewEveningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/summer-edit': {
      id: '/editorial/summer-edit'
      path: '/editorial/summer-edit'
      fullPath: '/editorial/summer-edit'
      preLoaderRoute: typeof EditorialSummerEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/shoreline-perspective': {
      id: '/editorial/shoreline-perspective'
      path: '/editorial/shoreline-perspective'
      fullPath: '/editorial/shoreline-perspective'
      preLoaderRoute: typeof EditorialShorelinePerspectiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/resort-2026': {
      id: '/editorial/resort-2026'
      path: '/editorial/resort-2026'
      fullPath: '/editorial/resort-2026'
      preLoaderRoute: typeof EditorialResort2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/mens-edit': {
      id: '/editorial/mens-edit'
      path: '/editorial/mens-edit'
      fullPath: '/editorial/mens-edit'
      preLoaderRoute: typeof EditorialMensEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/may-2026': {
      id: '/editorial/may-2026'
      path: '/editorial/may-2026'
      fullPath: '/editorial/may-2026'
      preLoaderRoute: typeof EditorialMay2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/accessories': {
      id: '/editorial/accessories'
      path: '/editorial/accessories'
      fullPath: '/editorial/accessories'
      preLoaderRoute: typeof EditorialAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/silk-scarves': {
      id: '/collections/silk-scarves'
      path: '/collections/silk-scarves'
      fullPath: '/collections/silk-scarves'
      preLoaderRoute: typeof CollectionsSilkScarvesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/luxury-sneakers': {
      id: '/collections/luxury-sneakers'
      path: '/collections/luxury-sneakers'
      fullPath: '/collections/luxury-sneakers'
      preLoaderRoute: typeof CollectionsLuxurySneakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/italian-leather-wallets': {
      id: '/collections/italian-leather-wallets'
      path: '/collections/italian-leather-wallets'
      fullPath: '/collections/italian-leather-wallets'
      preLoaderRoute: typeof CollectionsItalianLeatherWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/italian-leather-loafers': {
      id: '/collections/italian-leather-loafers'
      path: '/collections/italian-leather-loafers'
      fullPath: '/collections/italian-leather-loafers'
      preLoaderRoute: typeof CollectionsItalianLeatherLoafersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/italian-leather-handbags': {
      id: '/collections/italian-leather-handbags'
      path: '/collections/italian-leather-handbags'
      fullPath: '/collections/italian-leather-handbags'
      preLoaderRoute: typeof CollectionsItalianLeatherHandbagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/designer-sunglasses': {
      id: '/collections/designer-sunglasses'
      path: '/collections/designer-sunglasses'
      fullPath: '/collections/designer-sunglasses'
      preLoaderRoute: typeof CollectionsDesignerSunglassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/designer-mens-shirts': {
      id: '/collections/designer-mens-shirts'
      path: '/collections/designer-mens-shirts'
      fullPath: '/collections/designer-mens-shirts'
      preLoaderRoute: typeof CollectionsDesignerMensShirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/designer-crossbody-bags': {
      id: '/collections/designer-crossbody-bags'
      path: '/collections/designer-crossbody-bags'
      fullPath: '/collections/designer-crossbody-bags'
      preLoaderRoute: typeof CollectionsDesignerCrossbodyBagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/designer-belts': {
      id: '/collections/designer-belts'
      path: '/collections/designer-belts'
      fullPath: '/collections/designer-belts'
      preLoaderRoute: typeof CollectionsDesignerBeltsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/cashmere-sweaters': {
      id: '/collections/cashmere-sweaters'
      path: '/collections/cashmere-sweaters'
      fullPath: '/collections/cashmere-sweaters'
      preLoaderRoute: typeof CollectionsCashmereSweatersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/mens-swim': {
      id: '/campaign/mens-swim'
      path: '/campaign/mens-swim'
      fullPath: '/campaign/mens-swim'
      preLoaderRoute: typeof CampaignMensSwimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$vendor': {
      id: '/brand/$vendor'
      path: '/brand/$vendor'
      fullPath: '/brand/$vendor'
      preLoaderRoute: typeof BrandVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trending-brands': {
      id: '/admin/trending-brands'
      path: '/admin/trending-brands'
      fullPath: '/admin/trending-brands'
      preLoaderRoute: typeof AdminTrendingBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shopify-sync': {
      id: '/admin/shopify-sync'
      path: '/admin/shopify-sync'
      fullPath: '/admin/shopify-sync'
      preLoaderRoute: typeof AdminShopifySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo-health': {
      id: '/admin/seo-health'
      path: '/admin/seo-health'
      fullPath: '/admin/seo-health'
      preLoaderRoute: typeof AdminSeoHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/landing-pages': {
      id: '/admin/landing-pages'
      path: '/admin/landing-pages'
      fullPath: '/admin/landing-pages'
      preLoaderRoute: typeof AdminLandingPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory-sync': {
      id: '/admin/inventory-sync'
      path: '/admin/inventory-sync'
      fullPath: '/admin/inventory-sync'
      preLoaderRoute: typeof AdminInventorySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homepage-curation': {
      id: '/admin/homepage-curation'
      path: '/admin/homepage-curation'
      fullPath: '/admin/homepage-curation'
      preLoaderRoute: typeof AdminHomepageCurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/growth-os': {
      id: '/admin/growth-os'
      path: '/admin/growth-os'
      fullPath: '/admin/growth-os'
      preLoaderRoute: typeof AdminGrowthOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/email-recovery': {
      id: '/admin/email-recovery'
      path: '/admin/email-recovery'
      fullPath: '/admin/email-recovery'
      preLoaderRoute: typeof AdminEmailRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collection-image-qa': {
      id: '/admin/collection-image-qa'
      path: '/admin/collection-image-qa'
      fullPath: '/admin/collection-image-qa'
      preLoaderRoute: typeof AdminCollectionImageQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collection-image-preview': {
      id: '/admin/collection-image-preview'
      path: '/admin/collection-image-preview'
      fullPath: '/admin/collection-image-preview'
      preLoaderRoute: typeof AdminCollectionImagePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collection-hero-regression': {
      id: '/admin/collection-hero-regression'
      path: '/admin/collection-hero-regression'
      fullPath: '/admin/collection-hero-regression'
      preLoaderRoute: typeof AdminCollectionHeroRegressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collection-focal': {
      id: '/admin/collection-focal'
      path: '/admin/collection-focal'
      fullPath: '/admin/collection-focal'
      preLoaderRoute: typeof AdminCollectionFocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/recover': {
      id: '/account/recover'
      path: '/recover'
      fullPath: '/account/recover'
      preLoaderRoute: typeof AccountRecoverRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRoute
    }
    '/journal/style/the-investment-sunglasses-edit': {
      id: '/journal/style/the-investment-sunglasses-edit'
      path: '/style/the-investment-sunglasses-edit'
      fullPath: '/journal/style/the-investment-sunglasses-edit'
      preLoaderRoute: typeof JournalStyleTheInvestmentSunglassesEditRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/style/luxury-sneakers-as-modern-tailoring': {
      id: '/journal/style/luxury-sneakers-as-modern-tailoring'
      path: '/style/luxury-sneakers-as-modern-tailoring'
      fullPath: '/journal/style/luxury-sneakers-as-modern-tailoring'
      preLoaderRoute: typeof JournalStyleLuxurySneakersAsModernTailoringRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/craftsmanship/spot-real-italian-leather': {
      id: '/journal/craftsmanship/spot-real-italian-leather'
      path: '/craftsmanship/spot-real-italian-leather'
      fullPath: '/journal/craftsmanship/spot-real-italian-leather'
      preLoaderRoute: typeof JournalCraftsmanshipSpotRealItalianLeatherRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/craftsmanship/made-in-italy-vs-designed-in-italy': {
      id: '/journal/craftsmanship/made-in-italy-vs-designed-in-italy'
      path: '/craftsmanship/made-in-italy-vs-designed-in-italy'
      fullPath: '/journal/craftsmanship/made-in-italy-vs-designed-in-italy'
      preLoaderRoute: typeof JournalCraftsmanshipMadeInItalyVsDesignedInItalyRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/craftsmanship/caring-for-fine-leather': {
      id: '/journal/craftsmanship/caring-for-fine-leather'
      path: '/craftsmanship/caring-for-fine-leather'
      fullPath: '/journal/craftsmanship/caring-for-fine-leather'
      preLoaderRoute: typeof JournalCraftsmanshipCaringForFineLeatherRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$blogHandle/$articleHandle': {
      id: '/journal/$blogHandle/$articleHandle'
      path: '/$blogHandle/$articleHandle'
      fullPath: '/journal/$blogHandle/$articleHandle'
      preLoaderRoute: typeof JournalBlogHandleArticleHandleRouteImport
      parentRoute: typeof JournalRoute
    }
    '/api/public/seo-health': {
      id: '/api/public/seo-health'
      path: '/api/public/seo-health'
      fullPath: '/api/public/seo-health'
      preLoaderRoute: typeof ApiPublicSeoHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stock-alerts/subscribe': {
      id: '/api/public/stock-alerts/subscribe'
      path: '/api/public/stock-alerts/subscribe'
      fullPath: '/api/public/stock-alerts/subscribe'
      preLoaderRoute: typeof ApiPublicStockAlertsSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-collection-images': {
      id: '/api/public/hooks/sync-collection-images'
      path: '/api/public/hooks/sync-collection-images'
      fullPath: '/api/public/hooks/sync-collection-images'
      preLoaderRoute: typeof ApiPublicHooksSyncCollectionImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/shopify-order-created': {
      id: '/api/public/hooks/shopify-order-created'
      path: '/api/public/hooks/shopify-order-created'
      fullPath: '/api/public/hooks/shopify-order-created'
      preLoaderRoute: typeof ApiPublicHooksShopifyOrderCreatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/expire-shopify-tags': {
      id: '/api/public/hooks/expire-shopify-tags'
      path: '/api/public/hooks/expire-shopify-tags'
      fullPath: '/api/public/hooks/expire-shopify-tags'
      preLoaderRoute: typeof ApiPublicHooksExpireShopifyTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-cart-recovery': {
      id: '/api/public/hooks/dispatch-cart-recovery'
      path: '/api/public/hooks/dispatch-cart-recovery'
      fullPath: '/api/public/hooks/dispatch-cart-recovery'
      preLoaderRoute: typeof ApiPublicHooksDispatchCartRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/win-back-emails': {
      id: '/api/public/cron/win-back-emails'
      path: '/api/public/cron/win-back-emails'
      fullPath: '/api/public/cron/win-back-emails'
      preLoaderRoute: typeof ApiPublicCronWinBackEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-homepage-layout': {
      id: '/api/public/cron/refresh-homepage-layout'
      path: '/api/public/cron/refresh-homepage-layout'
      fullPath: '/api/public/cron/refresh-homepage-layout'
      preLoaderRoute: typeof ApiPublicCronRefreshHomepageLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/drain-growth-jobs': {
      id: '/api/public/cron/drain-growth-jobs'
      path: '/api/public/cron/drain-growth-jobs'
      fullPath: '/api/public/cron/drain-growth-jobs'
      preLoaderRoute: typeof ApiPublicCronDrainGrowthJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/back-in-stock-notify': {
      id: '/api/public/cron/back-in-stock-notify'
      path: '/api/public/cron/back-in-stock-notify'
      fullPath: '/api/public/cron/back-in-stock-notify'
      preLoaderRoute: typeof ApiPublicCronBackInStockNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/abandoned-cart-recovery': {
      id: '/api/public/cron/abandoned-cart-recovery'
      path: '/api/public/cron/abandoned-cart-recovery'
      fullPath: '/api/public/cron/abandoned-cart-recovery'
      preLoaderRoute: typeof ApiPublicCronAbandonedCartRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/recommendations': {
      id: '/api/public/ai/recommendations'
      path: '/api/public/ai/recommendations'
      fullPath: '/api/public/ai/recommendations'
      preLoaderRoute: typeof ApiPublicAiRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountLoginRoute: typeof AccountLoginRoute
  AccountRecoverRoute: typeof AccountRecoverRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountLoginRoute: AccountLoginRoute,
  AccountRecoverRoute: AccountRecoverRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface JournalRouteChildren {
  JournalBlogHandleArticleHandleRoute: typeof JournalBlogHandleArticleHandleRoute
  JournalCraftsmanshipCaringForFineLeatherRoute: typeof JournalCraftsmanshipCaringForFineLeatherRoute
  JournalCraftsmanshipMadeInItalyVsDesignedInItalyRoute: typeof JournalCraftsmanshipMadeInItalyVsDesignedInItalyRoute
  JournalCraftsmanshipSpotRealItalianLeatherRoute: typeof JournalCraftsmanshipSpotRealItalianLeatherRoute
  JournalStyleLuxurySneakersAsModernTailoringRoute: typeof JournalStyleLuxurySneakersAsModernTailoringRoute
  JournalStyleTheInvestmentSunglassesEditRoute: typeof JournalStyleTheInvestmentSunglassesEditRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalBlogHandleArticleHandleRoute: JournalBlogHandleArticleHandleRoute,
  JournalCraftsmanshipCaringForFineLeatherRoute:
    JournalCraftsmanshipCaringForFineLeatherRoute,
  JournalCraftsmanshipMadeInItalyVsDesignedInItalyRoute:
    JournalCraftsmanshipMadeInItalyVsDesignedInItalyRoute,
  JournalCraftsmanshipSpotRealItalianLeatherRoute:
    JournalCraftsmanshipSpotRealItalianLeatherRoute,
  JournalStyleLuxurySneakersAsModernTailoringRoute:
    JournalStyleLuxurySneakersAsModernTailoringRoute,
  JournalStyleTheInvestmentSunglassesEditRoute:
    JournalStyleTheInvestmentSunglassesEditRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface SwimRouteChildren {
  SwimSizeGuideRoute: typeof SwimSizeGuideRoute
}

const SwimRouteChildren: SwimRouteChildren = {
  SwimSizeGuideRoute: SwimSizeGuideRoute,
}

const SwimRouteWithChildren = SwimRoute._addFileChildren(SwimRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AuthenticationRoute: AuthenticationRoute,
  BrandsRoute: BrandsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  JournalRoute: JournalRouteWithChildren,
  LegalNoticeRoute: LegalNoticeRoute,
  LimitedFindsRoute: LimitedFindsRoute,
  LinksRoute: LinksRoute,
  LoginRoute: LoginRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  PrivacyRoute: PrivacyRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StyleQuizRoute: StyleQuizRoute,
  SwimRoute: SwimRouteWithChildren,
  TermsRoute: TermsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCollectionFocalRoute: AdminCollectionFocalRoute,
  AdminCollectionHeroRegressionRoute: AdminCollectionHeroRegressionRoute,
  AdminCollectionImagePreviewRoute: AdminCollectionImagePreviewRoute,
  AdminCollectionImageQaRoute: AdminCollectionImageQaRoute,
  AdminEmailRecoveryRoute: AdminEmailRecoveryRoute,
  AdminGrowthOsRoute: AdminGrowthOsRoute,
  AdminHomepageCurationRoute: AdminHomepageCurationRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminInventorySyncRoute: AdminInventorySyncRoute,
  AdminLandingPagesRoute: AdminLandingPagesRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSeoHealthRoute: AdminSeoHealthRoute,
  AdminShopifySyncRoute: AdminShopifySyncRoute,
  AdminTrendingBrandsRoute: AdminTrendingBrandsRoute,
  BrandVendorRoute: BrandVendorRoute,
  CampaignMensSwimRoute: CampaignMensSwimRoute,
  CollectionsHandleRoute: CollectionsHandleRoute,
  CollectionsCashmereSweatersRoute: CollectionsCashmereSweatersRoute,
  CollectionsDesignerBeltsRoute: CollectionsDesignerBeltsRoute,
  CollectionsDesignerCrossbodyBagsRoute: CollectionsDesignerCrossbodyBagsRoute,
  CollectionsDesignerMensShirtsRoute: CollectionsDesignerMensShirtsRoute,
  CollectionsDesignerSunglassesRoute: CollectionsDesignerSunglassesRoute,
  CollectionsItalianLeatherHandbagsRoute:
    CollectionsItalianLeatherHandbagsRoute,
  CollectionsItalianLeatherLoafersRoute: CollectionsItalianLeatherLoafersRoute,
  CollectionsItalianLeatherWalletsRoute: CollectionsItalianLeatherWalletsRoute,
  CollectionsLuxurySneakersRoute: CollectionsLuxurySneakersRoute,
  CollectionsSilkScarvesRoute: CollectionsSilkScarvesRoute,
  EditorialAccessoriesRoute: EditorialAccessoriesRoute,
  EditorialMay2026Route: EditorialMay2026Route,
  EditorialMensEditRoute: EditorialMensEditRoute,
  EditorialResort2026Route: EditorialResort2026Route,
  EditorialShorelinePerspectiveRoute: EditorialShorelinePerspectiveRoute,
  EditorialSummerEditRoute: EditorialSummerEditRoute,
  EditorialTheNewEveningRoute: EditorialTheNewEveningRoute,
  EditorialVersaceRoute: EditorialVersaceRoute,
  EditorialVersaceNowRoute: EditorialVersaceNowRoute,
  EditorialWomensEditRoute: EditorialWomensEditRoute,
  ProductHandleRoute: ProductHandleRoute,
  AdminIndexRoute: AdminIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ApiPublicSeoHealthRoute: ApiPublicSeoHealthRoute,
  ApiPublicAiRecommendationsRoute: ApiPublicAiRecommendationsRoute,
  ApiPublicCronAbandonedCartRecoveryRoute:
    ApiPublicCronAbandonedCartRecoveryRoute,
  ApiPublicCronBackInStockNotifyRoute: ApiPublicCronBackInStockNotifyRoute,
  ApiPublicCronDrainGrowthJobsRoute: ApiPublicCronDrainGrowthJobsRoute,
  ApiPublicCronRefreshHomepageLayoutRoute:
    ApiPublicCronRefreshHomepageLayoutRoute,
  ApiPublicCronWinBackEmailsRoute: ApiPublicCronWinBackEmailsRoute,
  ApiPublicHooksDispatchCartRecoveryRoute:
    ApiPublicHooksDispatchCartRecoveryRoute,
  ApiPublicHooksExpireShopifyTagsRoute: ApiPublicHooksExpireShopifyTagsRoute,
  ApiPublicHooksShopifyOrderCreatedRoute:
    ApiPublicHooksShopifyOrderCreatedRoute,
  ApiPublicHooksSyncCollectionImagesRoute:
    ApiPublicHooksSyncCollectionImagesRoute,
  ApiPublicStockAlertsSubscribeRoute: ApiPublicStockAlertsSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
